//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTP_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
    }
}
