//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDBFirstApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Emps
    {
        public int Emp_ID { get; set; }
        public string Emp_Name { get; set; }
        public int Emp_Age { get; set; }
        public Nullable<int> Emp_FK_Dept_ID { get; set; }
    
        public virtual tbl_Dept tbl_Dept { get; set; }
    }
}
