//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConceptAcademy02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student
    {
        public int Std_Id { get; set; }
        public string Std_Name { get; set; }
        public int Std_Age { get; set; }
        public string Department { get; set; }
    }
}
