//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConceptAcademy04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int Emp_ID { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Add { get; set; }
        public Nullable<int> Emp_Dept { get; set; }
    
        public virtual tbl_Dept tbl_Dept { get; set; }
    }
}
