//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMultipleTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dept
    {
        public int Dept_Id { get; set; }
        public string Dept_Name { get; set; }
        public Nullable<int> Emp_Dept { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
